src/ioinit.o.d:  \
 /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/ecos/packages/io/common/current/src/ioinit.cxx \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/io/io.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/pkgconf/system.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/pkgconf/hal.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/pkgconf/hal_mips_pb44.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/pkgconf/hal_mips_ar7100.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/pkgconf/hal_mips_mips32.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/pkgconf/hal_mips.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/infra/cyg_type.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/stddef.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/build/mipsisa32-elf/lib/gcc-lib/mipsisa32-elf/3.2.1/include/stddef.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/hal/basetype.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/error/codes.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/pkgconf/error.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/io/devtab.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/hal/drv_api.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/hal/hal_tables.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/hal/hal_arch.h \
  /home/fanjianqi/atheros_work/reference/trunk_11_6_22/boot/redboot/rom_bld/install/include/cyg/hal/var_arch.h
