#ifndef CYGONCE_PKGCONF_HAL_MIPS_H
#define CYGONCE_PKGCONF_HAL_MIPS_H
/*
 * File <pkgconf/hal_mips.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_ARCH_PROGRAM_NEW_STACK hal_arch_program_new_stack
#define CYGINT_HAL_MIPS_VARIANT 1
#define CYGINT_HAL_MIPS_VARIANT_1
#define CYGHWR_HAL_MIPS_CPU_FREQ 400
#define CYGHWR_HAL_MIPS_CPU_FREQ_400
#define CYGDBG_HAL_MIPS_DEBUG_GDB_CTRLC_SUPPORT 1
#define CYGSEM_HAL_MIPS_EMULATE_UNIMPLEMENTED_FPU_OPS 1
#define CYGINT_HAL_MIPS_INTERRUPT_RETURN_KEEP_SR_IM 0
#define CYGINT_HAL_MIPS_INTERRUPT_RETURN_KEEP_SR_IM_0
#define CYGSEM_REDBOOT_MIPS_LINUX_BOOT 1
#define CYGDAT_REDBOOT_MIPS_LINUX_BOOT_ENTRY 0x80100750
#define CYGDAT_REDBOOT_MIPS_LINUX_BOOT_ENTRY_0x80100750
#define CYGDAT_REDBOOT_MIPS_LINUX_BOOT_ARGV_ADDR 0x80050000
#define CYGDAT_REDBOOT_MIPS_LINUX_BOOT_ARGV_ADDR_0x80050000
#define CYGDAT_REDBOOT_MIPS_LINUX_BOOT_COMMAND_LINE console=ttyS0,115200 root=31:02 rootfstype=jffs2 init=/sbin/init lm75.force=0,0x48 board=ja76hx

#endif
