#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_MIPS current
#define CYGPKG_HAL_MIPS_current
#define CYGNUM_HAL_MIPS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_MIPS_VERSION_MINOR -1
#define CYGNUM_HAL_MIPS_VERSION_RELEASE -1
#define CYGPKG_HAL_MIPS_MIPS32 current
#define CYGPKG_HAL_MIPS_MIPS32_current
#define CYGNUM_HAL_MIPS_MIPS32_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_MIPS_MIPS32_VERSION_MINOR -1
#define CYGNUM_HAL_MIPS_MIPS32_VERSION_RELEASE -1
#define CYGPKG_HAL_MIPS_AR7100 current
#define CYGPKG_HAL_MIPS_AR7100_current
#define CYGNUM_HAL_MIPS_AR7100_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_MIPS_AR7100_VERSION_MINOR -1
#define CYGNUM_HAL_MIPS_AR7100_VERSION_RELEASE -1
#define CYGPKG_HAL_MIPS_PB44 current
#define CYGPKG_HAL_MIPS_PB44_current
#define CYGNUM_HAL_MIPS_PB44_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_MIPS_PB44_VERSION_MINOR -1
#define CYGNUM_HAL_MIPS_PB44_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_mips_pb44.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_mips_ar7100.h>
#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_mips_pb44_ram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_mips_pb44_ram.h>
#define CYGPKG_DEVS_ETH_MIPS_MIPS32_AR7100 current
#define CYGPKG_DEVS_ETH_MIPS_MIPS32_AR7100_current
#define CYGNUM_DEVS_ETH_MIPS_MIPS32_AR7100_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_ETH_MIPS_MIPS32_AR7100_VERSION_MINOR -1
#define CYGNUM_DEVS_ETH_MIPS_MIPS32_AR7100_VERSION_RELEASE -1
#define CYGPKG_DEVS_FLASH_AR7100 current
#define CYGPKG_DEVS_FLASH_AR7100_current
#define CYGNUM_DEVS_FLASH_AR7100_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_FLASH_AR7100_VERSION_MINOR -1
#define CYGNUM_DEVS_FLASH_AR7100_VERSION_RELEASE -1
#define CYGPKG_HAL current
#define CYGPKG_HAL_current
#define CYGNUM_HAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_VERSION_MINOR -1
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_INFRA current
#define CYGPKG_INFRA_current
#define CYGNUM_INFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_INFRA_VERSION_MINOR -1
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_REDBOOT current
#define CYGPKG_REDBOOT_current
#define CYGNUM_REDBOOT_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_REDBOOT_VERSION_MINOR -1
#define CYGNUM_REDBOOT_VERSION_RELEASE -1
#define CYGNUM_HAL_VIRTUAL_VECTOR_AUX_CHANNELS 1
#define CYGPKG_ISOINFRA current
#define CYGPKG_ISOINFRA_current
#define CYGNUM_ISOINFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ISOINFRA_VERSION_MINOR -1
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING current
#define CYGPKG_LIBC_STRING_current
#define CYGNUM_LIBC_STRING_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STRING_VERSION_MINOR -1
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_CRC current
#define CYGPKG_CRC_current
#define CYGNUM_CRC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_CRC_VERSION_MINOR -1
#define CYGNUM_CRC_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC current
#define CYGPKG_MEMALLOC_current
#define CYGNUM_MEMALLOC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_MEMALLOC_VERSION_MINOR -1
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_COMPRESS_ZLIB current
#define CYGPKG_COMPRESS_ZLIB_current
#define CYGNUM_COMPRESS_ZLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_COMPRESS_ZLIB_VERSION_MINOR -1
#define CYGNUM_COMPRESS_ZLIB_VERSION_RELEASE -1
#define CYGPKG_COMPRESS_7ZIP current
#define CYGPKG_COMPRESS_7ZIP_current
#define CYGNUM_COMPRESS_7ZIP_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_COMPRESS_7ZIP_VERSION_MINOR -1
#define CYGNUM_COMPRESS_7ZIP_VERSION_RELEASE -1
#define CYGPKG_IO_ETH_DRIVERS current
#define CYGPKG_IO_ETH_DRIVERS_current
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MINOR -1
#define CYGNUM_IO_ETH_DRIVERS_VERSION_RELEASE -1
#define CYGPKG_IO_FILEIO current
#define CYGPKG_IO_FILEIO_current
#define CYGNUM_IO_FILEIO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_FILEIO_VERSION_MINOR -1
#define CYGNUM_IO_FILEIO_VERSION_RELEASE -1
#define CYGPKG_IO_FLASH current
#define CYGPKG_IO_FLASH_current
#define CYGNUM_IO_FLASH_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_FLASH_VERSION_MINOR -1
#define CYGNUM_IO_FLASH_VERSION_RELEASE -1
#define CYGPKG_IO current
#define CYGPKG_IO_current
#define CYGNUM_IO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_VERSION_MINOR -1
#define CYGNUM_IO_VERSION_RELEASE -1
#define CYGPKG_ERROR current
#define CYGPKG_ERROR_current
#define CYGNUM_ERROR_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ERROR_VERSION_MINOR -1
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_LINUX_COMPAT current
#define CYGPKG_LINUX_COMPAT_current
#define CYGNUM_LINUX_COMPAT_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LINUX_COMPAT_VERSION_MINOR -1
#define CYGNUM_LINUX_COMPAT_VERSION_RELEASE -1

#endif
